### ISSUE TITLE
lmao bhai compile kaise karoon?

### ISSUE THREAD

**Issue by compiler-ullman** [Gourab-Ghosh/timecat-cpp#1]
assets kidhar hai madaarchod (teri gaand mei hai kya?)

# MAKEFILE KA NAAM SUNA HAI?

lawde `run.sh` kya hota hai?

bhai git kyu use krr ra hai agar `.bak` file banani hai?

:clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face:

**Comment by Gourab-Ghosh** [comment]
> assets kidhar hai madaarchod (teri gaand mei hai kya?)
> 
> # MAKEFILE KA NAAM SUNA HAI?
> lawde `run.sh` kya hota hai?
> 
> bhai git kyu use krr ra hai agar `.bak` file banani hai?
> 
> clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face

This is only testing project for my engine. So I never seriously made it usable for others. The main project is moved to the rust version. Check that. Also MAKEFILE is much more painful than the simple comand cargo run. So I never made it. Also I never made this repo for others to use. It is only for my cv.

**Comment by Gourab-Ghosh** [comment]
> assets kidhar hai madaarchod (teri gaand mei hai kya?)
> 
> # MAKEFILE KA NAAM SUNA HAI?
> lawde `run.sh` kya hota hai?
> 
> bhai git kyu use krr ra hai agar `.bak` file banani hai?
> 
> clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face clown_face

I didn't expect others to test my engine as it was not so good at that time. So I had never written anything seriously. But now I have updated the readme file. Hope it answers all your questions.

**Comment by compiler-ullman** [comment]
@Gourab-Ghosh sorry uwu 🥺
